"""init: core tables

Revision ID: 514f9f31aab1
Revises: 
Create Date: 2026-06-18 13:17:24.359564
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = '514f9f31aab1'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
